BlogProject/BlogProject.Web/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using BlogProject.Web.ViewModels.Auth;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BlogProject.Web.Controllers
{
    public class AuthController : Controller
    {

        private IHttpClientFactory _httpClientFactory;

        public AuthController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel login)
        {
            if (!ModelState.IsValid)
            {
                return View(login);
            }

            var _client = _httpClientFactory.CreateClient("BlogClient");
            var jsonBody = JsonConvert.SerializeObject(login);
            var content = new StringContent(jsonBody, Encoding.UTF8, "application/json");
            var response = _client.PostAsync("/Api/Auth", content).Result;
            if (response.IsSuccessStatusCode)
            {
                var token = response.Content.ReadAsStringAsync().Result;
                var claims = new List<Claim>()
                {
                  
                    new Claim(ClaimTypes.NameIdentifier,login.UserName),
                    new Claim(ClaimTypes.Name,login.UserName),
                    new Claim("AccessToken",token)
                };
                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var principal = new ClaimsPrincipal(identity);
                var properties = new AuthenticationProperties
                {
                    IsPersistent = true,
                    AllowRefresh = true
                };
                HttpContext.SignInAsync(principal, properties);
                return Redirect("/Home");
            }
            else
            {
                ModelState.AddModelError("Username", "User Not Valid");
                return View(login);
            }





        }
    }
}

BlogProject/BlogProject.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BlogProject.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BlogProject/BlogProject.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
<a asp-action="login" asp-controller="Auth" class="btn btn-primary">ورود</a>

BlogProject/BlogProject.Web/Views/Shared/_DefaultLayout.cshtml
<!DOCTYPE html>
<html class="no-js" dir="rtl" lang="fa-IR">
<head>
    <meta charset="UTF-8">
    <title> سایت خبری برنامه نویسان </title>
    <base href="">
    <meta name="googlebot" content="index,follow">
    <meta name="robots" content="noodp,noydir">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap-rtl.min.css">
    <link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/css/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <script src="/js/jquery.min.js"></script>
</head>
<body>
    <script src="js/modernizr.js"></script>

    <!-- Top Menu -->
    <div class="top-menu">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-5">
                        <ul>
                            <li><a href=""><i class="fa fa-home"></i></a></li>
                            <li><a href=""><i class="fa fa-question-circle"></i></a></li>
                            <li><a href=""><i class="fa fa-envelope"></i></a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-7">
                        <span>امروز : 18/08/1395</span>
                    </div>
                </div>
            </div>
        </div>
    <!-- End Top Menu -->
    <!-- header -->
    <header class="main-header">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <a href="" class="logo"><img src="img/logo.png" alt="" title=""></a>
                        <div class="left-side">
                            <h1><a href="">سایت خبری برنامه نویسان</a></h1>
                            <h2> پایگاه اطلاع رسانی و خبری</h2>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <form action="/Search" method="get" class="border-radius">
                            <input class="border-radius" name="q" type="text" placeholder=" جستجو کنید ... ">
                            <button><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </header>
    <!-- End Header -->
    <!-- menu -->
    @*<nav class="main-menu">
            <div class="container">
                <span><i class="fa fa-th-list"></i></span>
                <partial name="_ShowGroupsInMenu"/>
            </div>
        </nav>*@
    <!-- End menu -->

    <div class="container margin-top-30">
        <div class="row">

            <aside class="col-md-4 col-sm-12 col-xs-12 pull-right">

                @*@await Component.InvokeAsync("ShowGroupsComponent")*@
                <!-- most views news -->
                @*@await Component.InvokeAsync("ShowTopPageComponent")*@

                <!-- end most views news -->
            </aside>


            <div class="col-md-8 col-sm-12 col-xs-12 ">

                @RenderBody()

            </div>


        </div>
    </div>

    <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-12 col-xs-12">
                        <section class="access-links">
                            <header> دسترسی سریع </header>
                            <ul>
                                <li><a href=""> صفحه اصلی </a></li>
                                <li><a href=""> قوانین سایت  </a></li>
                                <li><a href=""> راهنمای سایت  </a></li>
                                <li><a href=""> پیوندهای سایت </a></li>
                                <li><a href=""> صفحه اصلی </a></li>
                                <li><a href=""> قوانین سایت  </a></li>
                                <li><a href=""> صفحه اصلی </a></li>
                                <li><a href=""> قوانین سایت  </a></li>
                                <li><a href=""> راهنمای سایت  </a></li>
                            </ul>
                        </section>
                    </div>
                    <div class="col-md-5 col-md-offset-1 col-sm-12 col-xs-12">
                        <div class="socials">
                            <span> شبکه های اجتماعی  سایت</span>
                            <a href=""><i class="fa fa-facebook"></i></a>
                            <a href=""><i class="fa fa-twitter"></i></a>
                            <a href=""><i class="fa fa-paper-plane"></i></a>
                            <a href=""><i class="fa fa-google-plus"></i></a>
                            <div class="clearfix"></div>
                        </div>
                        <p>
                            تمامی حقوق مادی و معنوی این طرح متعلق به آموزشگاه برنامه نویسان می باشد و کپی برداری از این طرح غیر اخلاقی می باشد.
                        </p>
                    </div>
                </div>
            </div>
        </footer>

    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/owl.carousel.js"></script>
    <script src="/js/script.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>